Xitong_django_test/Xitong_django_test/urls.py
# -*- coding:utf-8 -*-
"""Xitong_django_test URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.views.static import serve #处理静态文件的

from django.views.generic import TemplateView
from users.views import LoginView,RegisterView,ActiveView,ForgetpwdView,ResetView,ModifyView,LogoutView,IndexView
from organization.views import OrgView
from Xitong_django_test.settings import MEDIA_ROOT,STATIC_ROOT
import xadmin

urlpatterns = [
    # url(r'^xadmin/', xadmin.site.urls),

    url(r'^xadmin/', include(xadmin.site.urls), name='xadmin'),


    url(r'^$',IndexView.as_view(),name='index'),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$',ActiveView.as_view(),name='useractive'),
    url(r'forgetpwd/$',ForgetpwdView.as_view(),name='forgetpwd'),
    url(r'^reset/(?P<active_code>.*)/$',ResetView.as_view(),name='resetpwd'),
    url(r'modify/$',ModifyView.as_view(),name='modifypwd'),

    # #课程机构首页
    # url(r'^org_list/$',OrgView.as_view(),name = 'org_list'),
    #课程机构url配置
    url(r'^org/',include('organization.urls_organization',namespace='org')), #Namespace命名空间  避免出现命名问题

    #处理添加图片的url,配置上传文件的访问处理
    url(r'^media/(?P<path>.*)$',serve,{'document_root':MEDIA_ROOT}),

    #static文件的访问
    url(r'^static/(?P<path>.*)$',serve,{'document_root':STATIC_ROOT}),

    #公开课url设置
    url(r'^course/',include('courses.url_courses',namespace='course')),

    # #讲师相关url设置
    # url(r'^teacher/',include('courses.url_courses',namespace='course')),

    #个人中心url设置
    url(r'^users/',include('users.url_users',namespace='users')),

]

#全局404頁面
handler404 = 'users.views.page404'   #還需要在setting中設置DEBUG為false

Xitong_django_test/apps/courses/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime

from organization.models import CourseOrg,Teacher

from django.db import models

# Create your models here.


class Course(models.Model):   #课程数据库
    #添加一个外键
    course_org = models.ForeignKey(CourseOrg,verbose_name=u'课程机构',null=True,blank=True)  #这里需要添加null.blank是因为这个表里面早又数据，而添加数据这样不会出错
    name = models.CharField(max_length=50,verbose_name=u'课程名')
    desc = models.CharField(max_length=300,verbose_name=u'课程描述')
    detail = models.TextField(u'课程详情')
    degree = models.CharField(choices=(('cj',u'初级'),('zj',u'中级'),('gj',u'高级')),max_length=20)
    learn_time = models.IntegerField(default=0,verbose_name=u'学习时长（课时）')
    students = models.IntegerField(default=0,verbose_name=u'学习人数')
    fav_mums = models.IntegerField(default=0,verbose_name=u'收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m',verbose_name=u'封面图',max_length=100)
    click_nums = models.IntegerField(default=0,verbose_name=u'点击数')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')
    course_type = models.CharField(default=u'后端开发',max_length=30,verbose_name=u'课程类别')
    teacher = models.ForeignKey(Teacher,verbose_name=u'讲师',null=True,blank=True)
    youneed_known =models.CharField(max_length=300,verbose_name=u'课程须知',default='')
    teacher_tellyou = models.CharField(max_length=300,verbose_name=u'老师告诉你能学到什么',default='')
    isbanner = models.BooleanField(default=False,verbose_name=u'是否輪播')

    class Meta:
        verbose_name = u'课程名称'
        verbose_name_plural = verbose_name

    def lesson_zj_nums(self):  #章节数统计
        return self.lesson_set.all().count()

    def lean_stu_user(self):  #取出学习用户 在operation中的usercourse里
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):  #获取课程所有章节
        return self.lesson_set.all()

    def __unicode__(self):
        return  self.name


class Lesson(models.Model):
    course = models.ForeignKey(Course,verbose_name=u'课程名')
    name = models.CharField(max_length=100, verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def get_lesson_vido(self):
        return self.video_set.all()

    def __unicode__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson,verbose_name=u'章节')
    name = models.CharField(max_length=100,verbose_name=u'视频名')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course,verbose_name=u'课程')
    name = models.CharField(max_length=100,verbose_name=u'名称')
    download = models.FileField(upload_to='course/resource',verbose_name=u'资源文件',max_length=100)
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

Xitong_django_test/apps/organization/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime

from django.db import models

# Create your models here.

class CityDict(models.Model):
    name = models.CharField(max_length=20,verbose_name=u'城市')
    desc = models.CharField(max_length=200,verbose_name=u'描述')
    add_time = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = u'城市描述'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseOrg(models.Model):
    name = models.CharField(max_length=50,verbose_name=u'机构名称')
    desc = models.TextField(verbose_name=u'机构描述')
    click_nums = models.IntegerField(default=0,verbose_name=u'点击数')
    fav_nums = models.IntegerField(default=0,verbose_name=u'收藏数')
    image = models.ImageField(upload_to='org/%Y/%m',verbose_name=u'封面图')
    address = models.CharField(max_length=150,verbose_name=u'机构地址')
    city = models.ForeignKey(CityDict,verbose_name=u'所在城市')

    students = models.IntegerField(default=0, verbose_name=u'学习人数')
    course_nums = models.IntegerField(default=0, verbose_name=u'课程数')
    orgtype = models.CharField(default='pxjg',verbose_name=u'机构类别',max_length=100,choices=(('pxjg','培训机构'),('gr','个人'),('gx','高校')))


    class Meta:
        verbose_name = u'课程机构'
        verbose_name_plural = verbose_name

    def get_teacher_nums(self):  #获取课程机构的教师数量
        return self.teacher_set.all().count()

    def get_courese_nums(self):
        return self.course_set.all().count()

    def get_coursee_name(self):
        return self.course_set.all()[:2]  # 有外键就可以这么用



    def __unicode__(self):
        return self.name


class Teacher(models.Model):
    org = models.ForeignKey(CourseOrg,verbose_name=u'所属机构')
    name = models.CharField(max_length=50,verbose_name=u'教师名')
    work_years = models.IntegerField(default=0,verbose_name=u'工作年限')
    work_company = models.CharField(max_length=50,verbose_name=u'工作公司')
    worl_position = models.CharField(max_length=50,verbose_name=u'公司职位')
    points = models.CharField(max_length=50,verbose_name=u'教学特点')
    click_nums = models.IntegerField(default=0,verbose_name=u'点击数')
    fav_nums = models.IntegerField(default=0,verbose_name=u'收藏数')
    add_time = models.DateTimeField(default=datetime.now)
    image = models.ImageField(upload_to='teacher/%Y/%m', verbose_name=u'头像',default='')
    age = models.IntegerField(default=0,verbose_name=u'年龄')

    class Meta:
        verbose_name = u'教师'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

Xitong_django_test/apps/organization/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponse

#分页所需要的库
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from organization.models import CourseOrg,CityDict
from .forms import UserForm
from .models import Teacher
from courses.models import Course
# Create your views here.

class OrgView(View):
    #课程机构列表功能
    def get(self,request):
        #所有课程机构
        all_orgs = CourseOrg.objects.all()
        # 授课机构排名
        hot_orgs = all_orgs.order_by('-click_nums')[:3]


        # 搜索功能
        search_keywords = request.GET.get('keywords', '')
        if search_keywords:
            all_orgs = all_orgs.filter(name__icontains=search_keywords)  # icontains 中的i表示django里面一般都是不区分大小写



        #所有城市
        all_citys = CityDict.objects.all()
        #取出筛选城市
        city_id = request.GET.get('city', '')
        if city_id:
            all_orgs = all_orgs.filter(city_id=int(city_id))

        #筛选出机构类别
        orgtype = request.GET.get('ct', '')
        if orgtype:
            all_orgs = all_orgs.filter(orgtype=orgtype)

        sort = request.GET.get('sort', '')
        if sort:
            if sort == 'students':
                all_orgs = all_orgs.order_by('-students') # - 号代表倒叙排序
            elif sort == 'courses':
                all_orgs = all_orgs.order_by('-course_nums')


        org_nums = all_orgs.count()  #统计所有课程
        #分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        #objects = ['john', 'edward', 'josh', 'frank']

        # Provide Paginator with the request object for complete querystring generation

        p = Paginator(all_orgs,4, request=request)  #这里的5是每一页只显示5个

        orgs = p.page(page)





        return render(request,'org-list.html',{
            'all_orgs':orgs,
            'all_citys':all_citys,
            'org_nums':org_nums,
            'city_id':city_id,
            'orgtype':orgtype,
            'hot_orgs':hot_orgs,
            'sort':sort,
        })



class AddUserAskView(View):
    '''
    用户咨询
    '''
    def post(self,request):
        userask_form = UserForm(request.POST)
        if userask_form.is_valid():
            userask = userask_form.save(commit=True)  #直接保存到数据库里面去 commit为TRUE才能保存起
            return HttpResponse("{'status':'success'}",content_type='application/json')
        else:
            return HttpResponse('{"status":"fail","msg":"添加错误"}'.format(userask_form.errors),content_type='application/json')


class OrgHomeView(View):
    def get(self,request,org_id):
        page = 'home'
        course_org = CourseOrg.objects.get(id = int(org_id))
        course_org.click_nums += 1
        course_org.save()
        all_course = course_org.course_set.all()[:3]  #有外键就可以这么用
        all_teachers = course_org.teacher_set.all()[:3]
        return render(request,'org-detail-homepage.html',{
            'all_course':all_course,
            'all_teachers':all_teachers,
            'course_org':course_org,
            'page':page
        })



class OrgCourseView(View):
    def get(self,request,org_id):
        page = 'course'
        course_org = CourseOrg.objects.get(id = int(org_id))
        all_course = course_org.course_set.all()  #有外键就可以这么用
        return render(request,'org-detail-course.html',{
            'all_course': all_course,
            'course_org': course_org,
            'page':page
        })


class OrgDescView(View):
    def get(self,request,org_id):
        page = 'desc'
        course_org = CourseOrg.objects.get(id = int(org_id)) #有外键就可以这么用
        return render(request,'org-detail-desc.html',{
            'course_org': course_org,
            'page':page
        })


class OrgTeacherView(View):
    def get(self,request,org_id):
        page = 'teacher'
        course_org = CourseOrg.objects.get(id = int(org_id))
        all_teacher = course_org.teacher_set.all()  #有外键就可以这么用
        return render(request,'org-detail-teachers.html',{
            'all_teacher': all_teacher,
            'course_org': course_org,
            'page':page
        })


class TeacherListView(View):
    #课程讲师列表页
    def get(self,request):
        all_teachers = Teacher.objects.all()

        # 搜索功能
        search_keywords = request.GET.get('keywords', '')
        if search_keywords:
            all_teachers = all_teachers.filter(name__icontains=search_keywords)  # icontains 中的i表示django里面一般都是不区分大小写

        #排序
        sort = request.GET.get('sort','')
        if sort:
            if sort == 'hot':
                all_teachers = all_teachers.order_by('-click_nums')

        sort_teachers = Teacher.objects.order_by('-work_years')[:2]

        #计数
        teachers_nums = all_teachers.count()


        # 分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        # objects = ['john', 'edward', 'josh', 'frank']

        # Provide Paginator with the request object for complete querystring generation

        p = Paginator(all_teachers, 3, request=request)  # 这里的5是每一页只显示5个

        teachers = p.page(page)

        return render(request,'teachers-list.html',{
            'all_teachers':teachers,
            'page_teachers': teachers,
            'sort_teacher':sort_teachers,
            'sort':sort,
            'teacher_num':teachers_nums,
        })


class TeacherDetailView(View):
    #讲师详情页
    def get(self,request,teacher_id):
        teacher = Teacher.objects.get(id = int(teacher_id))
        teacher.click_nums += 1
        teacher.save()
         #拿到老师的课程
        all_courses = Course.objects.filter(teacher = teacher)

        sort_teachers = Teacher.objects.order_by('-work_years')[:2]
        return render(request,'teacher-detail.html',{
            'all_courses':all_courses,
            'sort_teacher': sort_teachers,
            'teacher':teacher,

        })

Xitong_django_test/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>链接失效</title>
</head>
<body>
<p>链接失效</p>

</body>
</html>

Xitong_django_test/templates/course-comment.html
{% extends 'base.html' %}
{% block title %}BOL杰在线学习网{% endblock %}
{% load staticfiles %}
{% block custom_bread%}
    <section>
        <div class="wp">
            <div class="crumbs">
			<ul>
				<li><a href="index.html">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>评论</li>
			</ul>
		</div>
        </div>
    </section>
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
    //添加评论
    $('#js-pl-submit').on('click',function () {
        var comments = $('#js-pl-textarea').text()
        if (comments == ""){
            alert("评论不能为空")
            return
        }
        $.ajax({
            cache:false,
            type:"POST",
            url:{% url 'course:add_comment' %},
            data:{'course_id':{{ course.id }},'comments':comments},
            async:true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken","{{ csrf_token }}");
            },
            success: function (data) {
                if (data.status == 'fail'){
                    if (data.msg == '用户未登录'){
                        window.location.href="/login/";
                    }else {
                        alert(data.msg)
                    }
                }else if(data.status == 'success'){
                    window.location.reload(); //刷新页面
                }
            },
        });
    });
</script>
{% endblock %}


{% block content %}
    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_time }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                        </div>
                        <input type="button"  id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">

                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='../media/image/2016/12/default_big_14.png' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">bobby</span>
                                    </div>
                                    <p class="cnt">看到第三章了，虽然有些知识还不是听得很懂，但是感觉很有用的样子，想的是先听完一遍再说。然后再来听第二遍。最后想说老师棒棒哒！！！</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">时间：2016年12月13日 22:14</span>
                                    </div>
                                </div>
                            </li>

                        </ul>
                    </div>

                </div>
                <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for resoure in all_resourse %}
                                <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resoure.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resoure.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}



                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.worl_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.youneed_known }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tellyou }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/11/540e57300001d6d906000338-240-135_n0L8vbw.jpg" alt="django与vuejs实战项目2">
                                            <span class="name autowrap">django与vuejs实战项目2</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/python面向对象.jpg" alt="python面向对象">
                                            <span class="name autowrap">python面向对象</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/python文件处理.jpg" alt="python文件处理">
                                            <span class="name autowrap">python文件处理</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/11/mysql.jpg" alt="django入门">
                                            <span class="name autowrap">django入门</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/mysql.jpg" alt="xadmin进阶开发">
                                            <span class="name autowrap">xadmin进阶开发</span>
                                        </a>
                                    </li>

                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>
{% endblock %}

Xitong_django_test/templates/org-detail-desc.html
{% extends 'org_base.html' %}
{% load staticfiles %}
<li>{% block page_path %}机构介绍{% endblock %}</li>
{% block custom_title %}BOL杰在线学习网{% endblock %}

{% block right_form %}
    <div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">

            <p><p>&nbsp;{{ course_org.desc }} &nbsp;</p><h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"></h1></p>

        </div>
    </div>
{% endblock %}

Xitong_django_test/templates/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BOL杰在线学习网</title>
</head>
<body>
<p>邮件已发送请查收</p>
</body>
</html>

Xitong_django_test/templates/video.html
{#{% extends 'base.html' %}#}
{#{% block title %}贯勇杰在线首页{% endblock %}#}
{#{% load staticfiles %}#}
{#{% block custom_bread%}#}
{#    <section>#}
{#        <div class="wp">#}
{#            <ul  class="crumbs">#}
{#                <li><a href="index.html">首页</a>></li>#}
{#                <li>公开课</li>#}
{#            </ul>#}
{#        </div>#}
{#    </section>#}
{#{% endblock %}#}
{##}
{#{% block content %}#}
{#<body  overflow="">#}
{#    <div  class="bg503 ones">#}
{#        <video src="../static/video/JavaScript函数的定义.mp4" controls="controls"  height="520px" width="830px">#}
{#    </video>#}
{#    </div>#}
{#</body>#}
{#{% endblock %}#}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#    <link rel="stylesheet" type="text/css" href="../css/reset.css">#}
{#	<link rel="stylesheet" type="text/css" href="../css/animate.css">#}
{#	<link rel="stylesheet" type="text/css" href="../static/css/style.css">#}
{##}
{##}
{#</head>`#}
{#<body class="bg503 ones" overflow="">#}
{#<div  >#}
{#    <video src="../static/video/JavaScript函数的定义.mp4" controls="controls"  height="520px" width="830px">#}
{#    </video>#}
{#</div>#}
{#</body>#}
{#</html>#}

<!--视频居中最佳标准 830 * 520-->

<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>BOL杰在线学习网</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style1.css' %}">
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
</head>
<body class="bg503 ones " overflow="">
<div >
    <video  src="{% static 'video/JavaScript.mp4' %}" controls="controls"  height="520px" width="830px">
    </video>
</div>
</body>

</html>